### ISSUE TITLE
建议首页增加一个随机pop烂梗的选项卡

### ISSUE THREAD

**Issue by TieZhuzhu** [9WiSHao/sb6657#5]
可以增加一个功能，随机pop出一个烂梗
![image](https://github.com/9WiSHao/sb6657/assets/53392232/6e148a9f-be62-40c2-a5d2-60df7338d3f4)

**Comment by 9WiSHao** [comment]
实际上现在每次刷新网页，进入分类都是随机排序的烂梗，不过加一个也行

**Comment by 9WiSHao** [comment]
首页随机一条烂梗，整了

**Comment by TieZhuzhu** [comment]
> 首页随机一条烂梗，整了

好啊，你整得好哇，十分甚至有九分好！
