### ISSUE TITLE
可以加一个鼠标悬浮时高亮此行的功能

### ISSUE THREAD

**Issue by TheToiletsWar** [9WiSHao/sb6657#7]
内容比较多的时候，可能点复制的时候点击不到正确的行
![image](https://github.com/9WiSHao/sb6657/assets/65486245/4d44b302-50ec-4454-9bc9-82890536b08c)

**Comment by 9WiSHao** [comment]
ok，顺带加个点击烂梗文字也能复制

**Comment by 9WiSHao** [comment]
done
