### ISSUE TITLE
我能不能通过在部署仓里直接pull提交烂梗（

### ISSUE THREAD

**Issue by dankyu-fly** [9WiSHao/sb6657#8]
如题

**Comment by 9WiSHao** [comment]
别
首先那就是vue编译后版本，现阶段更新是直接源码里加完然后再编译，这么提交的话直接难以更新维护数据
然后就是静态页面版本马上不用了，现在在重构前后端分离版本的，那个仓库后面就没数据了，只有页面
之后烂梗提交会方便很多的，页面直接会有提交页
